export type INTENT_HARVEST = "HARVEST";
export type INTENT_UPGRADE = "UPGRADE";
export type INTENT_DEPOSIT = "DEPOSIT";
export type INTENT_BUILD = "BUILD";

export declare const INTENT_HARVEST: INTENT_HARVEST;
export declare const INTENT_UPGRADE: INTENT_UPGRADE;
export declare const INTENT_DEPOSIT: INTENT_DEPOSIT;

// export type CREEP_INTENTS = INTENT_HARVEST | INTENT_UPGRADE | INTENT_DEPOSIT | INTENT_BUILD
export type HARVESTER_INTENTS = INTENT_HARVEST | INTENT_DEPOSIT
export type BUILDER_INTENTS = INTENT_HARVEST | INTENT_BUILD | INTENT_DEPOSIT
export type UPGRADER_INTENTS = INTENT_HARVEST | INTENT_UPGRADE | INTENT_DEPOSIT