type ROLE_HARVESTER = "HARVESTER";
type ROLE_UPGRADER = "UPGRADER";
type ROLE_BUILDER = "BUILDER";
type ROLE_TOILER = "TOILER";
type ROLE_HAULER = "HAULER";

type WORKER_ROLES = ROLE_HARVESTER | ROLE_UPGRADER | ROLE_BUILDER | ROLE_TOILER | ROLE_HAULER;