type STATE_NEW = "NEW";
type STATE_SEEKSOURCE = "SEEKSOURCE";
type STATE_SEEKHOME = "SEEKHOME";
type STATE_RELOCATE = "RELOCATE";
type STATE_GATHER = "GATHER";
type STATE_UNLOAD = "UNLOAD";
type STATE_SEEKFRAME = "SEEKFRAME";
type STATE_CONSTRUCT = "CONSTRUCT";
type STATE_SEEKCONTROLLER = "SEEKCONTROLLER";
type STATE_PROMOTE = "PROMOTE";
type STATE_SEEKFREESTORE = "SEEKFREESTORE";
type STATE_SEEKFULLSTORE = "SEEKFULLSTORE";
type STATE_DUMP = "DUMP";
type STATE_SEEKTOILER = "SEEKTOILER";
type STATE_SEEKDROPPEDENERGY = "SEEKDROPPEDENERGY";

type HARVESTER_STATES = STATE_NEW | STATE_SEEKSOURCE | STATE_SEEKHOME | STATE_SEEKFREESTORE | STATE_RELOCATE | STATE_GATHER | STATE_UNLOAD;
type BUILDER_STATES = STATE_CONSTRUCT | STATE_GATHER | STATE_NEW | STATE_RELOCATE | STATE_SEEKFRAME | STATE_SEEKFULLSTORE | STATE_SEEKSOURCE;
type TOILER_STATES = STATE_NEW | STATE_DUMP | STATE_GATHER;
type UPGRADER_STATES = STATE_NEW | STATE_SEEKSOURCE | STATE_SEEKCONTROLLER | STATE_RELOCATE | STATE_GATHER | STATE_PROMOTE;
type HAULER_STATES = STATE_NEW | STATE_RELOCATE | STATE_SEEKFREESTORE | STATE_SEEKTOILER | STATE_SEEKDROPPEDENERGY;

type WORKER_STATES = HARVESTER_STATES | BUILDER_STATES | UPGRADER_STATES | TOILER_STATES | HAULER_STATES;