type INTENT_HARVEST = "HARVEST";
type INTENT_UPGRADE = "UPGRADE";
type INTENT_DEPOSIT = "DEPOSIT";
type INTENT_BUILD = "BUILD";
type INTENT_WITHDRAW = "WITHDRAW";
type INTENT_TOIL = "TOIL";
type INTENT_FETCH = "FETCH";

type HARVESTER_INTENTS = INTENT_HARVEST | INTENT_DEPOSIT;
type BUILDER_INTENTS = INTENT_HARVEST | INTENT_BUILD | INTENT_DEPOSIT | INTENT_WITHDRAW;
type UPGRADER_INTENTS = INTENT_HARVEST | INTENT_UPGRADE | INTENT_DEPOSIT;
type TOILER_INTENTS = INTENT_TOIL;
type HAULER_INTENTS = INTENT_FETCH | INTENT_DEPOSIT;

type WORKER_INTENTS = HARVESTER_INTENTS | BUILDER_INTENTS | UPGRADER_INTENTS | TOILER_INTENTS | HAULER_INTENTS;